[Config]
BuildCommand = make clean && make 1
Executable = 1
RunCommand = spike --isa=RV64GCV $RISCV/riscv64-unknown-linux-gnu/bin/pk 1 {input} > {output} && spike --isa=RV64GCV $RISCV/riscv64-unknown-linux-gnu/bin/pk 1 {input} $(echo {input} | sed 's/1_/2_/')

Inputs = ../testcases/input/1_*.txt
AnswerDir = ../testcases/expected/
AnswerExtension = .out

DiffCommand = diff -u {answer} {output}

TempOutputDir = ../output
DeleteTempOutput = true

ExitOrLog = log
ScoreDict = {"0":"0","1":"10", "2": "20"}
TotalScore = 30
Timeout = 10
